name: train_tracked_api
description: A better UK train tracking API
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

dependencies:
  date_time_format: ^2.0.1
  http: ^1.1.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  xml: ^6.4.2
  xml2json: ^6.2.1
  yaml: ^3.1.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
